@startuml
interface CatalogoBiblioteca {
    + buscarLibro(isbn: String): Libro
}

class CatalogoAdapter
class CatalogoCETYSServicio

CatalogoBiblioteca <|.. CatalogoAdapter
CatalogoAdapter --> CatalogoCETYSServicio
@enduml